spring:
  application:
    name: enotes
  profiles:
    active: prod
---
# dev Config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hritik@2002
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


file:
  upload:
    path: notes/
---
# test Config
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hritik@2002
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


file:
  upload:
    path: notes/
---
# prod Config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hritik@2002
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


file:
  upload:
    path: notes/
---
# uat Config
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hritik@2002
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload:
    path: notes/