spring:
  application:
    name: enotes
  profiles:
    active: prod
---
# dev Config
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${MYSQL_AIVEN_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: ${MYSQL_AIVEN_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    port: 587
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans,loggers
file:
  upload:
    path: notes/
admin:
  email: hritikchji@gmail.com
  password: ${EMAIL_PASSWORD}
frontend:
  url: http://localhost:5173

---
# test Config
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hritik@2002
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

file:
  upload:
    path: notes/
---
# prod Config
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MYSQL_AIVEN_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: ${MYSQL_AIVEN_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc

server:
  port: 8082
file:
  upload:
    path: /notes
admin:
  email: hritikchji@gmail.com
  password: ${EMAIL_PASSWORD}
frontend:
  url: ${FRONTEND_URL}

---
# uat Config
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hritik@2002
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB 
  mail:
    host: smtp.gmail.com
    username: hritikchji@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    path: /enotes-doc
  api-docs:
    path: /enotes-api-doc
file:
  upload:
    path: notes/